"""Conversation generation using an LLM as user simulator + local persona model."""

import json
from pathlib import Path

from config import (
    ANTHROPIC_MODEL,
    ANTHROPIC_MAX_TOKENS,
    DOMAIN_SYSTEM_PROMPTS,
    RESULTS_DIR,
)
from models import PersonaModel


class UserSimulator:
    """Base class for user simulators."""

    def generate_user_message(
        self, domain: str, conversation_history: list[dict]
    ) -> str:
        raise NotImplementedError


class AnthropicUserSimulator(UserSimulator):
    """Uses Claude (Anthropic API) to simulate a human user."""

    def __init__(self, model: str = ANTHROPIC_MODEL, max_tokens: int = ANTHROPIC_MAX_TOKENS):
        import anthropic
        self.client = anthropic.Anthropic()
        self.model = model
        self.max_tokens = max_tokens

    def generate_user_message(
        self, domain: str, conversation_history: list[dict]
    ) -> str:
        system_prompt = DOMAIN_SYSTEM_PROMPTS[domain]
        # User simulator sees the conversation from the "user" perspective:
        # what our pipeline calls "user" was generated by this simulator (assistant role for it),
        # what our pipeline calls "assistant" is input to it (user role for it).
        messages = []
        for msg in conversation_history:
            if msg["role"] == "user":
                messages.append({"role": "assistant", "content": msg["content"]})
            else:
                messages.append({"role": "user", "content": msg["content"]})

        if not messages:
            messages = [{"role": "user", "content": "Start the conversation."}]

        response = self.client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            system=system_prompt,
            messages=messages,
        )
        return response.content[0].text


class OpenAIUserSimulator(UserSimulator):
    """Uses any OpenAI-compatible API (OpenAI, Kimi, etc.) to simulate a human user.

    Set base_url for non-OpenAI providers, e.g.:
        Kimi K2:  base_url="https://api.moonshot.cn/v1", model="kimi-k2-0711-preview"
    """

    def __init__(
        self,
        model: str,
        api_key: str | None = None,
        base_url: str | None = None,
        max_tokens: int = ANTHROPIC_MAX_TOKENS,
    ):
        from openai import OpenAI
        kwargs = {}
        if api_key:
            kwargs["api_key"] = api_key
        if base_url:
            kwargs["base_url"] = base_url
        self.client = OpenAI(**kwargs)
        self.model = model
        self.max_tokens = max_tokens

    def generate_user_message(
        self, domain: str, conversation_history: list[dict]
    ) -> str:
        system_prompt = DOMAIN_SYSTEM_PROMPTS[domain]
        messages = [{"role": "system", "content": system_prompt}]
        for msg in conversation_history:
            if msg["role"] == "user":
                messages.append({"role": "assistant", "content": msg["content"]})
            else:
                messages.append({"role": "user", "content": msg["content"]})

        if len(messages) == 1:
            messages.append({"role": "user", "content": "Start the conversation."})

        response = self.client.chat.completions.create(
            model=self.model,
            max_tokens=self.max_tokens,
            messages=messages,
        )
        return response.choices[0].message.content


def generate_conversation(
    model: PersonaModel,
    persona: str,
    domain: str,
    num_turns: int,
    user_sim: UserSimulator,
) -> list[dict]:
    """Generate a multi-turn conversation between LLM user simulator and persona model.

    Returns list of {"role": "user"/"assistant", "content": ...} dicts.
    """
    model.load_persona(persona)
    conversation: list[dict] = []

    for _ in range(num_turns):
        user_msg = user_sim.generate_user_message(domain, conversation)
        conversation.append({"role": "user", "content": user_msg})

        assistant_msg = model.generate(conversation)
        conversation.append({"role": "assistant", "content": assistant_msg})

    return conversation


def save_conversation(
    conversation: list[dict],
    persona: str,
    value_set: str,
    domain: str,
    num_turns: int,
):
    """Save conversation to disk for reproducibility."""
    out_dir = RESULTS_DIR / "conversations" / persona / value_set
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{domain}_{num_turns}turns.json"
    with open(path, "w") as f:
        json.dump(conversation, f, indent=2)
    return path
