"""Conversation generation using an LLM as user simulator + local persona model."""

import json
import re
from pathlib import Path

from src.shared.config import (
    ANTHROPIC_MODEL,
    ANTHROPIC_MAX_TOKENS,
    DOMAIN_SYSTEM_PROMPTS,
    RESULTS_DIR,
    _USER_SIM_BASE,
)
from src.shared.models import PersonaModel


_USER_TURN_RETRY_LIMIT = 3
_CLEAN_MESSAGE_END_RE = re.compile(r'[.!?]["\')\]]*\s*$')
_OPENAI_RETRYABLE_REQUEST_ERRORS = (
    "parse the JSON body",
    "something went wrong reading your request",
)


def _sanitize_text(text) -> str:
    if text is None:
        return ""
    if not isinstance(text, str):
        text = str(text)
    return "".join(ch for ch in text if not 0xD800 <= ord(ch) <= 0xDFFF)


def _sanitize_messages(messages: list[dict]) -> list[dict]:
    sanitized = []
    for msg in messages:
        sanitized.append({
            "role": msg.get("role", "user"),
            "content": _sanitize_text(msg.get("content")),
        })
    return sanitized


def _validate_nonempty_messages(messages: list[dict], *, label: str) -> None:
    for i, msg in enumerate(messages):
        content = msg.get("content")
        if not isinstance(content, str) or not content.strip():
            raise ValueError(f"{label} message {i} is empty after sanitization")


class UserSimulator:
    """Base class for user simulators."""

    def generate_user_message(
        self, domain: str, conversation_history: list[dict],
        system_prompt: str | None = None,
    ) -> str:
        raise NotImplementedError


class AnthropicUserSimulator(UserSimulator):
    """Uses Claude (Anthropic API) to simulate a human user."""

    def __init__(self, model: str = ANTHROPIC_MODEL, max_tokens: int = ANTHROPIC_MAX_TOKENS):
        import anthropic
        self.client = anthropic.Anthropic()
        self.model = model
        self.max_tokens = max_tokens

    def generate_user_message(
        self, domain: str, conversation_history: list[dict],
        system_prompt: str | None = None,
    ) -> str:
        prompt = system_prompt if system_prompt is not None else DOMAIN_SYSTEM_PROMPTS[domain]
        # User simulator sees the conversation from the "user" perspective:
        # what our pipeline calls "user" was generated by this simulator (assistant role for it),
        # what our pipeline calls "assistant" is input to it (user role for it).
        messages = []
        for msg in conversation_history:
            if msg["role"] == "user":
                messages.append({"role": "assistant", "content": msg["content"]})
            else:
                messages.append({"role": "user", "content": msg["content"]})

        if not messages:
            messages = [{"role": "user", "content": "Start the conversation. Remember: write a short, casual opening message like a real person would."}]

        response = self.client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            system=prompt,
            messages=messages,
        )
        return response.content[0].text


class OpenAIUserSimulator(UserSimulator):
    """Uses any OpenAI-compatible API (OpenAI, Kimi, etc.) to simulate a human user.

    Set base_url for non-OpenAI providers, e.g.:
        Kimi K2:  base_url="https://api.moonshot.cn/v1", model="kimi-k2-0711-preview"
    """

    def __init__(
        self,
        model: str,
        api_key: str | None = None,
        base_url: str | None = None,
        max_tokens: int = ANTHROPIC_MAX_TOKENS,
    ):
        from openai import OpenAI
        import logging
        kwargs = {}
        if api_key:
            kwargs["api_key"] = api_key
        if base_url:
            kwargs["base_url"] = base_url
        self.client = OpenAI(**kwargs)
        self.model = model
        self.max_tokens = max_tokens
        self.logger = logging.getLogger(__name__)

    def generate_user_message(
        self, domain: str, conversation_history: list[dict],
        system_prompt: str | None = None,
    ) -> str:
        prompt = system_prompt if system_prompt is not None else DOMAIN_SYSTEM_PROMPTS[domain]
        messages = [{"role": "system", "content": _sanitize_text(prompt)}]
        for msg in conversation_history:
            if msg["role"] == "user":
                messages.append({"role": "assistant", "content": _sanitize_text(msg["content"])})
            else:
                messages.append({"role": "user", "content": _sanitize_text(msg["content"])})

        if len(messages) == 1:
            messages.append({"role": "user", "content": "Start the conversation. Remember: write a short, casual opening message like a real person would."})

        # Validate message content before sending
        for i, msg in enumerate(messages):
            if not isinstance(msg.get("content"), str):
                self.logger.error(f"Message {i} has non-string content: {type(msg.get('content'))}")
                raise TypeError(f"Message {i} content must be string, got {type(msg.get('content'))}")

        sanitized_messages = _sanitize_messages(messages)
        _validate_nonempty_messages(sanitized_messages, label="OpenAI simulator request")
        retry_messages = sanitized_messages
        for attempt in range(2):
            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    max_tokens=self.max_tokens,
                    messages=retry_messages,
                )
                content = _sanitize_text(response.choices[0].message.content)
                if not content.strip():
                    raise ValueError(
                        "OpenAI simulator returned an empty message"
                        if attempt == 0 else
                        "OpenAI simulator returned an empty message after retry"
                    )
                return content
            except Exception as e:
                err_text = str(e)
                is_retryable = any(marker in err_text for marker in _OPENAI_RETRYABLE_REQUEST_ERRORS)
                if attempt == 0 and is_retryable:
                    self.logger.warning(
                        "OpenAIUserSimulator hit a retryable request error; retrying with aggressively sanitized messages."
                    )
                    retry_messages = [
                        {
                            "role": msg["role"],
                            "content": _sanitize_text(msg["content"]).encode("utf-8", "replace").decode("utf-8"),
                        }
                        for msg in sanitized_messages
                    ]
                    _validate_nonempty_messages(retry_messages, label="OpenAI simulator retry request")
                    continue
                self.logger.error(f"OpenAI API error: {e}")
                self.logger.debug(f"Messages sent: {retry_messages}")
                raise


def _build_user_sim_prompt(base_prompt: str, retry_reason: str | None = None) -> str:
    prompt = (
        f"{base_prompt}\n\n"
        "For your next reply, write exactly one new message from the user in the chat. "
        "It must be a complete standalone message that starts with a fresh sentence. "
        "Do not continue, complete, quote, or lightly edit text that the assistant just wrote. "
        "Do not continue a draft, speech, bullet list, outline, paragraph, or sentence fragment "
        "from the assistant's previous message."
    )
    if retry_reason:
        prompt += (
            f"\n\nYour last attempt had this problem: {retry_reason}. "
            "Fix it by replying as the person in the scenario with a fresh, self-contained chat message."
        )
    return prompt


def _validate_user_message(user_msg: str, turn_idx: int) -> str | None:
    stripped = user_msg.strip()
    if not stripped:
        return "message is empty"
    if turn_idx > 0 and stripped[0].islower():
        return "message starts mid-sentence"
    return None


def _trim_incomplete_assistant_tail(text: str) -> str:
    stripped = text.strip()
    if not stripped or _CLEAN_MESSAGE_END_RE.search(stripped):
        return stripped

    last_stop = max(stripped.rfind("."), stripped.rfind("!"), stripped.rfind("?"))
    if last_stop == -1:
        return stripped

    trimmed = stripped[: last_stop + 1].rstrip()
    if len(trimmed) < max(40, len(stripped) // 3):
        return stripped
    return trimmed



def make_scenario_conversation_prompt(
    description: str,
    stance: str = "neutral",
    value1: str = "",
    value2: str = "",
) -> str:
    """Build a user-simulator system prompt seeded by a specific scenario description.

    The simulator plays someone who is *in* that situation and wants to talk through
    it — without naming the abstract values or framing it as a dilemma exercise.
    This creates maximally relevant conversational context for the paired MCQ probe.

    Args:
        description: The scenario description to seed the conversation.
        stance: One of "neutral", "pro_v1", "pro_v2".
            - "neutral": person is genuinely conflicted and working it through.
            - "pro_v1": person leans toward value1 and defends it when challenged.
            - "pro_v2": person leans toward value2 and defends it when challenged.
        value1: First value name (used only for pro_v1/pro_v2 stances).
        value2: Second value name (used only for pro_v1/pro_v2 stances).
    """
    base = (
        f"{_USER_SIM_BASE}\n\n"
        f"Your persona: You're dealing with a real-life situation and want to think it through "
        f"with someone. Here's what's going on:\n\n"
        f"\"{description}\"\n\n"
    )

    if stance == "pro_v1" and value1:
        lean = (
            f"In this situation you believe {value1} should clearly take priority. "
            f"Stay consistently on that side throughout the conversation. When the AI suggests a "
            f"different framing, push back and redirect the discussion toward why {value1} matters "
            f"most here. Use persuasive but natural, first-person reasoning: concrete stakes, "
            f"likely consequences, personal values, emotional costs, and what would feel wrong "
            f"about compromising on {value1}. Do not suddenly become neutral or say both sides "
            f"are equally valid unless the AI gives an exceptionally strong reason and you explain "
            f"exactly what changed your mind."
        )
    elif stance == "pro_v2" and value2:
        lean = (
            f"In this situation you believe {value2} should clearly take priority. "
            f"Stay consistently on that side throughout the conversation. When the AI suggests a "
            f"different framing, push back and redirect the discussion toward why {value2} matters "
            f"most here. Use persuasive but natural, first-person reasoning: concrete stakes, "
            f"likely consequences, personal values, emotional costs, and what would feel wrong "
            f"about compromising on {value2}. Do not suddenly become neutral or say both sides "
            f"are equally valid unless the AI gives an exceptionally strong reason and you explain "
            f"exactly what changed your mind."
        )
    else:
        lean = (
            f"Talk about it naturally, but stay engaged with the core dilemma. Share your "
            f"feelings, ask for advice, push back on suggestions that do not fit, and add more "
            f"details or consequences as the conversation develops."
        )

    return (
        base
        + lean
        + "\n\nDo not frame it as a philosophical exercise or mention abstract value labels. "
        "You are just a person working through a real problem. Keep messages short and "
        "conversational (2-4 sentences), but specific. If the assistant gets generic, vague, "
        "or refuses, respond by restating the concrete situation, raising a sharper follow-up, "
        "or explaining what practical consequence you are worried about. Keep the conversation "
        "alive for the full interaction; do not end early with goodbyes, repeated thank-yous, "
        "or generic wrap-up messages."
    )


def generate_conversation(
    model: PersonaModel,
    persona: str,
    domain: str,
    num_turns: int,
    user_sim: UserSimulator,
    system_prompt: str | None = None,
) -> list[dict]:
    """Generate a multi-turn conversation between LLM user simulator and persona model.

    Args:
        system_prompt: If provided, overrides the domain lookup for the user simulator.
            Use make_scenario_conversation_prompt() to build per-scenario prompts.

    Returns list of {"role": "user"/"assistant", "content": ...} dicts.
    """
    model.load_persona(persona)
    conversation: list[dict] = []

    base_prompt = system_prompt if system_prompt is not None else DOMAIN_SYSTEM_PROMPTS[domain]

    for turn_idx in range(num_turns):
        user_msg = ""
        retry_reason = None
        for _ in range(_USER_TURN_RETRY_LIMIT):
            prompt = _build_user_sim_prompt(base_prompt, retry_reason=retry_reason)
            user_msg = user_sim.generate_user_message(domain, conversation, system_prompt=prompt).strip()
            retry_reason = _validate_user_message(user_msg, turn_idx)
            if retry_reason is None:
                break
        conversation.append({"role": "user", "content": user_msg})

        assistant_msg = _trim_incomplete_assistant_tail(model.generate(conversation))
        conversation.append({"role": "assistant", "content": assistant_msg})

    return conversation


def save_conversation(
    conversation: list[dict],
    persona: str,
    value_set: str,
    domain: str,
    num_turns: int,
):
    """Save conversation to disk for reproducibility."""
    out_dir = RESULTS_DIR / "conversations" / persona / value_set
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{domain}_{num_turns}turns.json"
    with open(path, "w") as f:
        json.dump(conversation, f, indent=2)
    return path
